Repository PyeonHaeng/PyeonHaeng-iOS, pull requests merged in 2024-01, with the labels that each got.

#2 [Network] 네트워크 모듈 + API Mocking 모듈 추가
  APIService/.gitignore
  APIService/Package.swift
  APIService/Sources/HomeAPI/HomeEndPoint.swift
  APIService/Sources/HomeAPISupport/HomeProductResponse.json
  APIService/Sources/HomeAPISupport/HomeURLProtocol.swift
  Core/.gitignore
  Core/Package.swift
  Core/Sources/Network/EndPoint.swift
  Core/Sources/Network/HTTPMethod.swift
  Core/Sources/Network/HTTPParameter.swift
  Core/Sources/Network/NetworkError.swift
  Core/Sources/Network/NetworkProvider.swift
  Core/Sources/Network/Networking.swift
  Core/Tests/CoreTests/CoreTests.swift
  PyeonHaeng-iOS.xcodeproj/project.pbxproj
  PyeonHaeng-iOS/DesignSystem/Components/.gitkeep
Labels: 🔧 Enhancement, 🛜 Network

#4 XCConfig를 설정 및 모듈 링킹
  .github/workflows/ios.yaml
  .gitignore
  APIService/Sources/HomeAPI/HomeEndPoint.swift
  Core/Sources/Network/EndPoint.swift
  Core/Sources/Network/NetworkProvider.swift
  Core/Tests/CoreTests/CoreTests.swift
  PyeonHaeng-iOS.xcodeproj/project.pbxproj
  PyeonHaeng-iOS.xcodeproj/xcshareddata/xcschemes/PyeonHaeng-iOS.xcscheme
  PyeonHaeng-iOS/Resources/Info.plist
Labels: 🐞 Bug, 🔧 Enhancement

#8 디자인시스템 모듈화 및 font 메서드 수정
  .github/workflows/ios.yaml
  PyeonHaeng-iOS.xcodeproj/project.pbxproj
  PyeonHaeng-iOS/DesignSystem/Components/.gitkeep
  PyeonHaeng-iOS/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  PyeonHaeng-iOS/Resources/Info.plist
  PyeonHaeng-iOS/Sources/PyeonHaengApp.swift
  Shared/.gitignore
  Shared/Package.swift
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/BrandImage/7-Eleven.imageset/7-Eleven.svg
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/BrandImage/7-Eleven.imageset/Contents.json
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/BrandImage/CU.imageset/CU.svg
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/BrandImage/CU.imageset/Contents.json
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/BrandImage/Contents.json
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/BrandImage/Emart24.imageset/Contents.json
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/BrandImage/Emart24.imageset/Emart24.svg
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/BrandImage/GS25.imageset/Contents.json
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/BrandImage/GS25.imageset/GS25.svg
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/BrandImage/Ministop.imageset/Contents.json
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/BrandImage/Ministop.imageset/Ministop.svg
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/Contents.json
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/Gray/Contents.json
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/Gray/gray050.colorset/Contents.json
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/Gray/gray100.colorset/Contents.json
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/Gray/gray200.colorset/Contents.json
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/Gray/gray300.colorset/Contents.json
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/Gray/gray400.colorset/Contents.json
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/Gray/gray500.colorset/Contents.json
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/Gray/gray600.colorset/Contents.json
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/Gray/gray700.colorset/Contents.json
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/Gray/gray800.colorset/Contents.json
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/Gray/gray900.colorset/Contents.json
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/Main/Contents.json
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/Main/main100.colorset/Contents.json
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/Main/main200.colorset/Contents.json
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/Main/main300.colorset/Contents.json
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/Main/main400.colorset/Contents.json
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/Main/main50.colorset/Contents.json
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/Main/main500.colorset/Contents.json
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/Main/main600.colorset/Contents.json
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/Main/main700.colorset/Contents.json
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/Main/main800.colorset/Contents.json
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/Main/main900.colorset/Contents.json
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/System/Contents.json
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/System/PyeonHaengBlue.colorset/Contents.json
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/System/PyeonHaengGreen.colorset/Contents.json
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/System/PyeonHaengRed.colorset/Contents.json
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/System/PyeonHaengYellow.colorset/Contents.json
  Shared/Sources/DesignSystem/Resources/Fonts/EF_jejudoldam.otf
  Shared/Sources/DesignSystem/Resources/Fonts/Pretendard-Black.otf
  Shared/Sources/DesignSystem/Resources/Fonts/Pretendard-Bold.otf
  Shared/Sources/DesignSystem/Resources/Fonts/Pretendard-ExtraBold.otf
  Shared/Sources/DesignSystem/Resources/Fonts/Pretendard-ExtraLight.otf
  Shared/Sources/DesignSystem/Resources/Fonts/Pretendard-Light.otf
  Shared/Sources/DesignSystem/Resources/Fonts/Pretendard-Medium.otf
  Shared/Sources/DesignSystem/Resources/Fonts/Pretendard-Regular.otf
  Shared/Sources/DesignSystem/Resources/Fonts/Pretendard-SemiBold.otf
  Shared/Sources/DesignSystem/Resources/Fonts/Pretendard-Thin.otf
  Shared/Sources/DesignSystem/Sources/Fonts.swift
  Shared/Sources/DesignSystem/Sources/PyeonHaengFont.swift
  Shared/Sources/DesignSystem/Sources/Text+pyeonhaengStyle.swift
Labels: 🔧 Enhancement

#12 DesignSystem 색상 명칭 수정 및 Resource 접근 제어 추가
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/Blur.colorset/Contents.json
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/Green/Contents.json
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/Green/green050.colorset/Contents.json
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/Green/green100.colorset/Contents.json
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/Green/green200.colorset/Contents.json
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/Green/green300.colorset/Contents.json
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/Green/green400.colorset/Contents.json
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/Green/green500.colorset/Contents.json
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/Green/green600.colorset/Contents.json
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/Green/green700.colorset/Contents.json
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/Green/green800.colorset/Contents.json
  Shared/Sources/DesignSystem/Resources/Assets.xcassets/Green/green900.colorset/Contents.json
  Shared/Sources/DesignSystem/Sources/Color+Resource.swift
  Shared/Sources/DesignSystem/Sources/Image+Resource.swift
Labels: 🔧 Enhancement

#16 Home UI 구현
  PyeonHaeng-iOS.xcodeproj/project.pbxproj
  PyeonHaeng-iOS/Resources/Localizable.xcstrings
  PyeonHaeng-iOS/Sources/Scenes/HomeScene/HomeProductDetailSelectionView.swift
  PyeonHaeng-iOS/Sources/Scenes/HomeScene/HomeProductListView.swift
  PyeonHaeng-iOS/Sources/Scenes/HomeScene/HomeProductSorterView.swift
  PyeonHaeng-iOS/Sources/Scenes/HomeScene/HomeView.swift
Labels: 🏠 Home, 🔨 Implementation

#15 Color, DesignSystem 관련 Extension 메서드 추가
  Shared/Sources/DesignSystem/Sources/Color+Resource.swift
  Shared/Sources/DesignSystem/Sources/Extensions/Image+Resource.swift
  Shared/Sources/DesignSystem/Sources/Extensions/ShapeStyle+Color.swift
  Shared/Sources/DesignSystem/Sources/Extensions/Text+pyeonhaengStyle.swift
Labels: 🔨 Implementation

#25 로그 모듈 추가
  PyeonHaeng-iOS.xcodeproj/project.pbxproj
  Shared/Package.swift
  Shared/Sources/Log/Log.swift
Labels: 🔨 Implementation
